Repository azooKey/azooKey, pull requests merged in 2023-10, with the labels that each got.

#320 [Feature] QwertyKeyViewのサジェストに薄いシャドウを追加
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyKeyView.swift
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyVariationsView.swift
Labels: design

#322 [Fix] 混入していたデバッグ用実装を削除
  AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickEnterKeyModel.swift
Labels: bug

#321 [Feature] 特別な日にスペシャルアイコンを表示
  AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/EmojiTabResultBar.swift
  AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/KeyboardBarView.swift
  AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/ResultBar.swift
  AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/TabBarButton.swift
  Resources/AzooKeyIcon-Regular.otf
Labels: design

#323 [Refactoring] delete unused codes for iOS 15
  AzooKeyCore/Sources/AzooKeyUtils/AzooKeyMessage.swift
  AzooKeyCore/Sources/KeyboardViews/View/SpecialTabs/ClipboardHistoryTab.swift
  AzooKeyCore/Sources/KeyboardViews/View/SpecialTabs/EmojiTab.swift
  AzooKeyCore/Sources/SwiftUIUtils/Availability.swift
  Keyboard/Display/InputManager.swift
  Keyboard/Display/KeyboardActionManager.swift
  Keyboard/Display/KeyboardViewController.swift
  MainApp/ContentView.swift
  MainApp/Customize/ManageCustardView.swift
  MainApp/Setting/AdditionalDict/AdditionalDictManageView.swift
  MainApp/Setting/AdditionalDict/AzooKeyUserDictionary.swift
  MainApp/Setting/KeyboardLayout/KeyboardLayoutSettingItemView.swift
  MainApp/Theme/ThemeShareView.swift
Labels: refactoring

#324 [Refactoring] SwiftUIのPhotosPickerでマニュアルの実装を置き換え
  MainApp/General/Pickers/PhotoPicker.swift
  MainApp/Theme/ThemeEditView.swift
  azooKey.xcodeproj/project.pbxproj
Labels: refactoring

#326 [Refactoring] `any P<T>`がiOS 16で利用可能になるので、導入する
  AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/CustomKeyboard.swift
  AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/SimpleKeyView/SimpleKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/SimpleKeyView/SimpleKeyView.swift
  AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/FlickDataProvider.swift
  AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/FlickKeyboardView.swift
  AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickAaKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickChangeKeyboardKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickEnterKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickKanaSymbolsKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickKeyModelProtocol.swift
  AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickKeyView.swift
  AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickKogakiKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickNextCandidateKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickSpaceKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickTabKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyAaKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyChangeKeyboardKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyEnterKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyFunctionalKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyKeyModelProtocol.swift
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyKeyView.swift
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyLanguageSwitchKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyNextCandidateKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyShiftKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertySpaceKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyTabKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/QwertyDataProvider.swift
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/QwertyKeyboardView.swift
  AzooKeyCore/Sources/KeyboardViews/View/SpecialTabs/EmojiTab.swift
  MainApp/Customize/EditingTenkeyCustardView.swift
Labels: refactoring

#325 [Refactoring] Use requestReviewAction instead of old impl
  MainApp/Customize/CustomizeTabView.swift
  MainApp/Setting/SettingTab.swift
Labels: refactoring

#327 [Feature] デザインを改善
  AzooKeyCore/Sources/KeyboardViews/AzooKeyIcon.swift
  MainApp/Customize/CustomizeTabWalkthrough.swift
  MainApp/Customize/EditingTabBarView.swift
  MainApp/EnableAzooKeyView/EnableAzooKeyView.swift
  MainApp/EnableAzooKeyView/EnableAzooKeyViewComponent.swift
  MainApp/General/Focus.swift
  MainApp/General/HeaderLogoView.swift
  MainApp/General/LargeButtonStyle.swift
  MainApp/Setting/CustomKeys/FlickCustomKeys/CustomKeySettingFlickKeyView.swift
  MainApp/Setting/CustomKeys/QwertyCustomKeys/QwertyCustomKeysItemView.swift
  MainApp/Setting/OpenSourceSoftwaresLicenseView.swift
  MainApp/Tips/TipsView.swift
  Resources/Localizable.xcstrings
Labels: design

#328 [Fix] broken layout
  MainApp/Customize/CustomizeTabWalkthrough.swift
Labels: design

#277 [Feature] キーボードを経由せずカーソルを動かした場合にカーソルバーを表示
  Keyboard/Display/InputManager.swift
  Keyboard/Display/KeyboardActionManager.swift
Labels: enhancement, design

#330 [Feature] 操作がない場合に自動でカーソルバーを非表示に変更
  AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/KeyboardBarView.swift
Labels: enhancement

#331 [BUG] カーソルバーに表示される文字が更新されなくなる問題を修正
  AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/ReflectStyleCursorBar.swift
Labels: bug

#332 [Bug] TemporalMessageViewが消えないことがある問題に対処
  AzooKeyCore/Sources/KeyboardViews/TemporalMessage.swift
  AzooKeyCore/Sources/KeyboardViews/View/Components/TemporalMessageView.swift
  AzooKeyCore/Sources/KeyboardViews/View/KeyboardView.swift
Labels: bug

#335 [Fix] CursorBar周りを整えた
  AzooKeyCore/Sources/KeyboardViews/VariableStates.swift
  AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/ReflectStyleCursorBar.swift
  Keyboard/Display/InputManager.swift
  Keyboard/Display/KeyboardActionManager.swift
Labels: bug, enhancement, design

#337 [Fix] KeyboardFeedbackの実装のうち、MainActorで実行する処理とそうでない処理を分別した
  AzooKeyCore/Sources/KeyboardViews/KeyboardFeedback.swift
Labels: enhancement

#338 [Design] キーボードフリック時のSuggestViewを変更
  AzooKeyCore/Sources/KeyboardViews/Design.swift
  AzooKeyCore/Sources/KeyboardViews/View/Components/KeyLabel.swift
  AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/CustomKeyboard.swift
  AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/FlickKeyboardView.swift
  AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/SuggestView/FlickSuggestView.swift
Labels: enhancement, design

#339 [Design] add dismiss delay to flick suggests
  AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickKeyView.swift
Labels: design

#341 [Feature] update infoを更新
  MainApp/UpdateInformationView.swift
Labels: documentation

#342 [Design] 着せ替えタブのデザインを改善
  MainApp/Theme/ThemeTab.swift
  Resources/Localizable.xcstrings
Labels: design

#343 [Design] カーソルバーのデザインとアニメーションを改善
  AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/ReflectStyleCursorBar.swift
Labels: enhancement, design

#344 [Design] 余白をKeyboardLayout非依存にした
  AzooKeyCore/Sources/KeyboardViews/Design.swift
  AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/CustomKeyboard.swift
  AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/FlickKeyboardView.swift
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/QwertyKeyboardView.swift
  AzooKeyCore/Sources/KeyboardViews/View/SpecialTabs/ClipboardHistoryTab.swift
  AzooKeyCore/Sources/KeyboardViews/View/SpecialTabs/EmojiTab.swift
  MainApp/Customize/EditingTenkeyCustardView.swift
Labels: design

#347 [Design] Qwertyのサジェストにアニメーションを追加
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyVariationsView.swift
Labels: design

#348 [Fix] TabManagerへのアクセスでBAD_ACCESSが発生している問題を修正
  AzooKeyCore/Sources/KeyboardViews/VariableStates.swift
Labels: bug

#349 [Feature] カーソルバーの自動非表示を隠し機能化
  AzooKeyCore/Sources/AzooKeyUtils/AzooKeyKeyboardViewExtension.swift
  AzooKeyCore/Sources/AzooKeyUtils/KeyboardSetting/BoolKeyboardSetting.swift
  AzooKeyCore/Sources/KeyboardViews/ApplicationSpecificKeyboardViewSettingProvider.swift
  AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/KeyboardBarView.swift
  Keyboard/Display/InputManager.swift
  MainApp/Setting/SettingTab.swift
Labels: design

#350 [Docs] Update info
  MainApp/UpdateInformationView.swift
Labels: documentation

#351 [Refactoring] swiftlintを適用
  AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/SimpleKeyView/SimpleKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/FlickKeyboard/KeyView/FlickChangeKeyboardKeyModel.swift
  AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/KeyboardBarView.swift
  AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/ReflectStyleCursorBar.swift
  AzooKeyCore/Sources/KeyboardViews/View/KeyboardBar/SliderStyleCursorBar.swift
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/KeyView/QwertyNextCandidateKeyModel.swift
  MainApp/Customize/CodableActionDataEditor.swift
  MainApp/Setting/OpenSourceSoftwaresLicenseView.swift
Labels: refactoring

#354 [Docs] Version 2.2のリリース日を確定
  MainApp/UpdateInformationView.swift
Labels: documentation
