Repository azooKey/azooKey, pull requests merged in 2024-02, with the labels that each got.

#404 [Feature] 外部から読み込んだテンキーのカスタムタブデータを編集できるように変更
  MainApp/Customize/CustardInformationView.swift
Labels: bug, enhancement

#406 [Feature] Add ITSAppUsesNonExemptEncryption=NO
  MainApp/Info.plist
Labels: tools

#407 [Feature] Privacy Manifestを追加
  MainApp/PrivacyInfo.xcprivacy
  azooKey.xcodeproj/project.pbxproj
Labels: tools

#409 [BUG] "…"を入力するキーのラベルが"・"になっている
  AzooKeyCore/Sources/KeyboardViews/View/QwertyKeyboard/QwertyDataProvider.swift
Labels: bug

#408 [Feature] Update Emoji data
  AzooKeyCore/Sources/KeyboardViews/View/SpecialTabs/EmojiTab.swift
  Gen/data/emoji-sequences.txt
  Gen/data/emoji-test.txt
  Gen/data/emoji-zwj-sequences.txt
  Gen/data/emoji_additional.tsv
  Gen/data/emoji_data.tsv
  Gen/data/ja.xml
  Gen/data/ja_derived.xml
  Gen/scripts/emoji.py
  Gen/scripts/emoji.xcfilelist
  MainApp/Setting/AdditionalDict/AdditionalDictManageView.swift
  azooKey.xcodeproj/project.pbxproj
Labels: enhancement

#411 [Feature] Update AZKKC version and support new text replacer API
  AzooKeyCore/Package.swift
  Keyboard/Display/InputManager.swift
Labels: enhancement

#405 [Feature] Add build workflow for iOS app
  .github/workflows/build.yml
Labels: tools

#415 [Feature] Version 2.2.3の情報を追加
  AzooKeyCore/Sources/AzooKeyUtils/AzooKeyMessage.swift
  AzooKeyCore/Sources/AzooKeyUtils/SharedStore.swift
  MainApp/ContentView.swift
  MainApp/UpdateInformationView.swift
Labels: enhancement

#430 [Feature] 改善されたスクロール式カスタムタブの編集UIを実装
  AzooKeyCore/Sources/AzooKeyUtils/Custard/UserMadeCustard.swift
  AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/CustomKeyboard.swift
  AzooKeyCore/Sources/KeyboardViews/View/CustomKeybaord/SimpleKeyView/SimpleKeyView.swift
  MainApp/Customize/CustardInformationView.swift
  MainApp/Customize/CustardInterfaceKeyEditor.swift
  MainApp/Customize/EditingScrollCustardView.swift
  MainApp/Customize/EditingTenkeyCustardView.swift
  Resources/Localizable.xcstrings
Labels: enhancement, design
